word:
    pattern:  /
    defaults: { _controller: "NinjaThesaurusThesaurusBundle:Word:index" }

word_show:
    pattern:  /{id}/afficher
    defaults: { _controller: "NinjaThesaurusThesaurusBundle:Word:show" }

word_new:
    pattern:  /nouveau
    defaults: { _controller: "NinjaThesaurusThesaurusBundle:Word:new" }

word_create:
    pattern:  /creation
    defaults: { _controller: "NinjaThesaurusThesaurusBundle:Word:create" }
    requirements: { _method: post }

word_edit:
    pattern:  /{id}/editer
    defaults: { _controller: "NinjaThesaurusThesaurusBundle:Word:edit" }

word_update:
    pattern:  /{id}/mise-a-jour
    defaults: { _controller: "NinjaThesaurusThesaurusBundle:Word:update" }
    requirements: { _method: post|put }

word_delete:
    pattern:  /{id}/supprimer
    defaults: { _controller: "NinjaThesaurusThesaurusBundle:Word:delete" }
    requirements: { _method: post|delete }
