CREATE OR REPLACE TYPE DESCRIPTEUR AS OBJECT
(LIBELLE VARCHAR2 (35),
CONSTRAINT DESCRIPTEUR_UNIQUE UNIQUE (LIBELLE))
NOT FINAL
NOT INSTANTIABLE
/

CREATE OR REPLACE TYPE DVEDETTE



TODO

méthodes à faire dans descripteur

GET_SYNONYMES
GET_FILS

référence du père == > attribu ?
