parameters:
#    ninja_thesaurus_thesaurus.example.class: NinjaThesaurus\ThesaurusBundle\Example

services:
#    ninja_thesaurus_thesaurus.example:
#        class: %ninja_thesaurus_thesaurus.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
